### ISSUE TITLE
resources survey discussion

### ISSUE THREAD

**Issue by GabrielPelletier** [OpenScienceOfficeHours/osoh_website#6]
Started this issue to add comment and discuss changes to the Resources Survey

### Area of Neuroscience :
[EDIT] Neuroimaging and Neuroinformatics (instead of Neuroinformatics)

### Where does your data come from:
[EDIT] Non-human Primates (instead of Primates)
[ADD] C. Elegans
[ADD] Drosophilia
[ADD] Stem Cells

### Data Type:
[ADD] Eye-Tracking
[ADD] Microscopy
[ADD] Clinical data

### In the SEARCH/PLAN stage, you can use this to:
[ADD] Find Open/Shared dataset to re-use

### In the ANALYSIS stage, people can use this to: 
[ADD] Data Visualization 
[ADD] Collaborate on analyses
 [ADD] Track organize analysis code

### In the WRITING and PUBLICATION stage, people can use this to:
[ADD] Share Data
[ADD] Share Code
[ADD] Share Methods/Protocols
[ADD] Make sure all research outputs are linked together and citable

### For OUTREACH, people can use this resource to: 
[ADD] Patient engagement and partnership

## [Add] a questions about the project Stage directly? or the broad category?
* This resource is mainly used at which stage of a project lifecycle? [Planning, Data Collection, Data Analysis, Publication/Dissemination, Outreach] 
*  AND/OR This resources mainly relates to: [Open Publishing, Open Data, Open Code, Open Hardware, Open Protocols, Outreach]

**Comment by heike-s** [comment]
I agree with most, but would change the following: 

Area of Neuroscience:
- To me, neuroinformatics & neuroimaging are not the same. I've used neuroinformatics to refer to omics data/experiments (e.g., transcriptomics, epigenetic research, genotypes, etc.), but from a quick google search it seems that this isn't necessarily how everyone uses it. For clarity, we can maybe use OMICS or bioinformatics instead?

Data Type:
- I had used this option 'Immunohistochemistry / In-Situ Hybridization / Other Imaging' rather than microscopy, but I believe we are referring to the same thing. We could use microscopy though for brevity?

**Comment by GabrielPelletier** [comment]
> I agree with most, but would change the following:
> 
> Area of Neuroscience:
> 
> * To me, neuroinformatics & neuroimaging are not the same. I've used neuroinformatics to refer to omics data/experiments (e.g., transcriptomics, epigenetic research, genotypes, etc.), but from a quick google search it seems that this isn't necessarily how everyone uses it. For clarity, we can maybe use OMICS or bioinformatics instead?

Oh ok, this is what you meant by Neuroinforamtics.
From my experience, Bioinformatics is what is typically used for everything related to OMICs data processing/analysis. At The Neuro, I have seen/heard people use NeuroBioinformatics to talk about OMICS specifically related to the Neurosciences, but it is quite a mouthful and I'm not sure if it's that common.

The term Neuroinformatics I have almost always seen/heard in the context of Brain imaging (MRI, EEG, MEG and the like), more specifically from those working on processing and analysis pipelines, reproducibility issues, databases and data sharing, and so on. But you are right that Neuroinformatics is not the same as neuroimaging for everyone and it can be confusing.

I suggest we add 
* OMICs and bioinformatics
* something else for what I refer to as Neuroinformatics (let's see what K thinks, that's pretty much exactly what their lab does).

> Data Type:
> 
> * I had used this option 'Immunohistochemistry / In-Situ Hybridization / Other Imaging' rather than microscopy, but I believe we are referring to the same thing. We could use microscopy though for brevity?

I had missed "Immunohistochemistry / In-Situ Hybridization / Other Imaging". Yes I suggest we replace with Microscopy.

**Comment by koudyk** [comment]
suggested addition (as Gabriel suggested):
## Page 3
1) This resource falls under the category of 
- Open Publishing
- Open Data
- Open Methods/Protocols
- Open Code/Software
- Open Hardware

**Comment by koudyk** [comment]
Suggested change:
Make (only) these questions mandatory, since these are the things displayed on the website:
- Name
- website home url
- github url
- logo url
- description
- resource category
- species
- data type/modality
